### ISSUE TITLE
feat: Font Size input formatter - Angular Brackets

### ISSUE THREAD

**Issue by rohanjsh** [rohanjsh/typeset#11]
**Description**

To introduce size inputs via input text 'Hello \*World\*<20>' should be produce an out of 'World' being bold and font size should be 20

**Requirements**

- [ ] Introduce angular brackets as size formatters
- [ ] Should accept only double value
- [ ] Compatible with escape characters
- [ ] Test cases for coverage

**Comment by FirdousNath** [comment]
https://github.com/rohanjsh/typeset/pull/35 PR raised
