### ISSUE TITLE
perf: We should remove mocktail from dependencies ASAP

### ISSUE THREAD

**Issue by FirdousNathTide** [rohanjsh/typeset#45]
**Description**

Mocktail should be moved to dev_dependencies.
<img width="1456" alt="Screenshot 2024-01-31 at 4 34 34 PM" src="https://github.com/rohanjsh/typeset/assets/157100562/f04f4543-b131-4aee-a884-22a3204c6e4b">

**Comment by FirdousNathTide** [comment]
it will ship unnecessary files along with typeset to user.

**Comment by rohanjsh** [comment]
Ohh, thanks for pointing this out! @FirdousNathTide
