### ISSUE TITLE
feat: Support for Newline

### ISSUE THREAD

**Issue by mikecasey12** [rohanjsh/typeset#53]
**Description**

There should be support for newline (\n), so one can insert a newline or multiple lines depending on need.

**Requirements**

- [ ] Newline support (\n)

**Additional Context**

So if I have a something like:
`TypeSet("Michael is good at coding.\n Coding is fun.")`. 

I should get this output: 
`Michael is good at coding.
Coding is fun.`

**Comment by abhishekpande234** [comment]
Unable to reproduce the issue. It's working for me.
For - `TypeSet("Michael is good at coding.\n Coding is fun.")`
Kindly see the attached Screenshot.

![1722871923737](https://github.com/user-attachments/assets/2118f0f1-ee46-4051-9efb-72981a06bcbf)
